services:
  - type: web
    name: clinica-saude-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOST
        value: ep-lingering-snow-amdfj4og.c-5.us-east-1.aws.neon.tech

      - key: DB_PORT
        value: 5432

      - key: DB_NAME
        value: neondb

      - key: DB_USER
        value: neondb_owner

      - key: DB_PASSWORD
        sync: false
